# Generated by Django 4.0 on 2022-02-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Job Title', max_length=16)),
                ('company_name', models.CharField(default='Zicta', max_length=64)),
                ('qualifications', models.CharField(default='Grade 12 Certificate', max_length=250)),
            ],
            options={
                'ordering': ['-job_title'],
            },
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@gmail.come', max_length=35)),
                ('qualifications', models.CharField(max_length=250)),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multipleselect.author')),
            ],
            options={
                'ordering': ['qualifications'],
            },
        ),
    ]
