# Generated by Django 4.0.2 on 2022-02-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multipleselect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=35)),
                ('job_title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.CharField(max_length=45)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipleselect.job')),
            ],
        ),
        migrations.AlterModelOptions(
            name='applicants',
            options={},
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='qualifications',
        ),
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='applicants',
            name='qualifications',
            field=models.ManyToManyField(to='multipleselect.Requirements'),
        ),
    ]
