# Generated by Django 4.0.2 on 2022-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleselect', '0002_job_requirements_alter_applicants_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='ZICTA', max_length=35),
        ),
    ]
