# Generated by Django 4.0.2 on 2022-02-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleselect', '0003_remove_job_email_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='qualifications',
            field=models.CharField(max_length=250),
        ),
    ]
